# Generated by Django 3.1.4 on 2022-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0009_auto_20220214_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('appointmentStatus', models.CharField(choices=[('booked', 'booked'), ('canceled', 'canceled')], default='booked', max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=20)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.doctordetails')),
                ('nonRegisteredPatient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.nonregisteredpatientdetails')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.patientdetails')),
            ],
        ),
    ]
