# Generated by Django 3.1.4 on 2022-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='appointmentTime',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (1, 1), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
    ]
