# Generated by Django 3.1.4 on 2022-02-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_auto_20220214_2014'),
        ('appointment', '0002_auto_20220215_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.doctordetails'),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='nonRegisteredPatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.nonregisteredpatientdetails'),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.patientdetails'),
        ),
    ]
