# Generated by Django 3.1.4 on 2022-02-05 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAuth', '0004_auto_20220205_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('cashier', 'cashier'), ('call-center', 'call-center'), ('pharmacy', 'pharmacy')], max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staffprofilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('neurosciences', 'neurosciences'), ('cardiovascular-medicine', 'cardiovascular-medicine'), ('pulmonology', 'pulmonology'), ('obstetrics-and-gynecology', 'obstetrics-and-gynecology'), ('orthopaedics', 'orthopaedics'), ('oncolog', 'oncolog'), ('dermatology', 'dermatology'), ('diabetes-and-endocrinology', 'diabetes-and-endocrinology'), ('ear-nose-throat-ent', 'ear-nose-throat-ent'), ('eye-care', 'eye-care'), ('gastroenterology', 'gastroenterology'), ('nutrition-and-dietetic', 'nutrition-and-dietetic'), ('nephrology', 'nephrology'), ('physiotherapy', 'physiotherapy'), ('urology', 'urology')], max_length=50)),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='doctorprofilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
