# Generated by Django 3.1.4 on 2022-02-14 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_auto_20220205_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRegisteredPatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phone', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)])),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
