# Generated by Django 3.1.4 on 2022-04-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_auto_20220214_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=100)),
                ('testDate', models.DateTimeField(auto_now_add=True)),
                ('testPic', models.ImageField(blank=True, null=True, upload_to='testReport')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.patientdetails')),
            ],
        ),
    ]
