# Generated by Django 3.1.4 on 2022-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0010_testreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='testPic',
            field=models.ImageField(upload_to='testReport'),
        ),
    ]
